# Creating DataFrames

Many ways to do it!

In [1]:
import pandas as pd
import numpy as np

In [2]:
data = np.random.random(size=(5, 3))
print(data)

# Common 2D array and columns method
df = pd.DataFrame(data=data, columns=["A", "B", "C"])
df

[[0.68579105 0.59865469 0.14172715]
 [0.54872268 0.77195196 0.45628508]
 [0.48644547 0.40885802 0.90232428]
 [0.21608558 0.74905961 0.73664846]
 [0.759563   0.53122114 0.95808435]]


A         B         C
0  0.685791  0.598655  0.141727
1  0.548723  0.771952  0.456285
2  0.486445  0.408858  0.902324
3  0.216086  0.749060  0.736648
4  0.759563  0.531221  0.958084

In [7]:
# A dictionary of columns
df = pd.DataFrame(data={"A": [1, 2, 3], "B": ["Sam", "Alex", "John"]})
df

A     B
0  1   Sam
1  2  Alex
2  3  John

In [5]:
# Or a list of rows (ie tuples) with a dtype
dtype = [("A", np.int), ("B", (np.str, 20))]
data = np.array([(1, "Sam"), (2, "Alex"), (3, "John")], dtype=dtype)
df = pd.DataFrame(data)
df

/var/folders/vz/hm4rpc2511zf9hs8777s6g080000gn/T/ipykernel_2151/858698331.py:2: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype = [("A", np.int), ("B", (np.str, 20))]
/var/folders/vz/hm4rpc2511zf9hs8777s6g080000gn/T/ipykernel_2151/858698331.py:2: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: h

A     B
0  1   Sam
1  2  Alex
2  3  John

In [8]:
# Or the dictionary based version of list of rows
data = [{"A": 1, "B": "Sam"}, {"A": 2, "B": "Alex"}, {"A": 3, "B": "John"}]
df = pd.DataFrame(data)
df

A     B
0  1   Sam
1  2  Alex
2  3  John